### ISSUE TITLE
Add bpp timesteps to galactic evolution 

### ISSUE THREAD

**Issue by TiaSinghania** [TomWagg/cogsworth#140]
**Describe the new feature you'd like**
We'd like to see the galactic evolution information at timesteps listed in the bpp data frame. Ex. the change in orbital velocity after a supernova explosion, accounting for the orbit around the galaxy. 

**Any suggestions for how to implement this**
Perhaps the orbital integration already has finer timesteps than what is returned, so just modifying what is written?

**Comment by TomWagg** [comment]
Yes we can absolutely do this! So by default the timesteps returned are just 1 Myr, but under the hood it's an adaptive integrator that is often taking much smaller steps. So there's probably 3 options here:

- **The quick and dirty:** Use scipy interpolation methods to just get timesteps in between those reported (this would probably be okay in most cases, but not near SNs)
- **The slow but easy:** Just set `timestep_size` in your `Population` to some small number and then re-run `perform_galactic_evolution`, for a small population this won't take too long and then you can just mask the resulting orbits for the bpp timesteps
- **The bespoke and optimal:** Slightly more of a hassle to set up but you could manually use `gala` to integrate the orbits forward from their starting locations but a specific set of timesteps rather than a fixed number
    - If you wanted to do this it would likely be worth just making these a parameter you could pass with `cogsworth`, happy to help implement this if you want to do it

I think option 2 is going to be the lowest effort and best choice unless you've got a *lot* of sources.
